### PR TITLE
Added configurable service timeout

### PR DESCRIPTION
**Pull request by holsee**
_Work item started @ BelfastElixir 21/05/2019_

Introduce support for specifying the timeout in milliseconds for a Service.

## DONE

* Add support for passing `timeout_ms` option to a `DMS.ping/2` function.
* Add default value of 5 seconds when option not specified.
* Pass timeout value on `:ping` message, update state and use in `kill_switch` creation call.
* Add validation for timeout value passed in (as it is on public API).
* Add test to validate default timeout value is used when override not provided.
* Add test to validate timeout option is used when override is provided.

## TODO

* Refactor `kill_switch` function into own module to allow time-based unit testing without `Proces.sleep` call. _Moved to: https://github.com/belfastelixir/DMS/issues/29_

### CODE REVIEW

**Comment by holsee** [comment]
I shall not force-push to this branch going forward to allow multiple contributors to this patch

**Comment by holsee** [comment]
Addresses: https://github.com/belfastelixir/DMS/issues/18

**Comment by swmcc** [comment]
This should now be complete - the first part..

ALSO RELATIVE NUMBERS IN VIM IS OK - THIS LOT ARE JUST HARSH BASTARDS!!!!!!

**Comment by holsee** [comment]
Regarding string length validation, we need to consider: 

``` elixir
iex(4)> String.duplicate("X", 1024) |> byte_size
1024
iex(5)> String.duplicate("🤘", 1024) |> byte_size
4096
iex(6)> String.duplicate("🤘", 1024) |> String.length
1024
```

Unless we enforce alphanumeric values, which I suspect we will be.

**Pull request merged**
